[build]
  command = "npm config set registry https://registry.npmjs.org/ && npm install --legacy-peer-deps --force --no-fund --no-audit && npm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "16.14.0"
  NPM_VERSION = "8.5.0"
  NPM_FLAGS = "--no-audit --legacy-peer-deps --force"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 